filing:
  outdir: "./eorsky_out/mwa_three_short_bl_30mk"
  clobber: False
freq:
  Nfreqs: 384
  start_freq: 100000000.0
  bandwidth:  30000000.0
telescope:
  array_layout: telescope_config/HERA65_layout.csv
  telescope_config_name: telescope_config/MWA65_config.yaml
sources:
  catalog: 'gaussian_eor_shell'
time:
  Ntimes: 7854   # 24 hours
  #Ntimes: 100   # 24 hours
  integration_time: 11.0
  start_time: 2458098.5521759833
select:
  bls: '[(0,11),(0,12),(11,12)]'

fov: 110   # Deg
Nskies: 10
sky_sigma: 0.031      # mwaK
Nside: 128
