filing:
  outdir: "./results/test_out"
  outfile_prefix: 'healvis'
  clobber: False
freq:
  Nfreqs: 20
  start_freq: 100000000.0
  bandwidth:  30000000.0
telescope:
  array_layout: telescope_config/HERA65_layout.csv
  telescope_config_name: telescope_config/HERA65_config.yaml
sources:
  catalog: 'gaussian_eor_shell'
skymodel:
    sigma: 0.031      # 31 mK
    Nside: 64
    savepath: 'flatspectrum.hdf5'
    ref_chan: 10
time:
  Ntimes: 5   # 24 hours
  integration_time: 11.0
  start_time: 2458098.5521759833
select:
  bls: '[(0,11),(0,12),(11,12)]'

fov: 110   # Deg
Nskies: 1
