# A healvis observation parameter file

# --- IO Parameters ---
filing:
  outdir: "./results/test_out"
  outfile_prefix: 'healvis'
  clobber: False

# -- Simulation Parameters ---
beam:
  # options are ["airy", "gaussian", "<filepath>"]
  beam_type: "airy"
  # additional params for 'airy' or 'gaussian'
  diameter: 15  # meters
  gauss_width: 5.0  # degrees
freq:
  Nfreqs: 20
  start_freq: 100000000.0
  bandwidth:  100000000.0
telescope:
  config_dir: "./scripts/telescope_config"
  array_layout: HERA65_layout.csv
  telescope_config_name: HERA65_config.yaml
time:
  Ntimes: 5
  integration_time: 100.0  # seconds
  start_time: 2458098.5521759833
select:
  bls: '[(0,11),(0,12),(11,12)]'
fov: 110   # Deg
Nskies: 1
sources:
  catalog: 'gaussian_eor_shell'

# --- SkyModel Parameters ---
skyparam:
  # options are ['flat_spec', 'gsm', '<filepath>']
  sky_type: 'gsm'
  ref_chan: 10
  # additional parmas if sky_type is flat_spec or gsm
  sigma: 0.031      # 31 mK
  Nside: 64
  savepath: 'flatspectrum.hdf5'

