filing:
  outdir: "./results/hera37_red_hex_30mk"
  clobber: False
freq:
  Nfreqs: 384
  start_freq: 100000000.0
  bandwidth:  30000000.0
telescope:
  array_layout: telescope_config/MWA_east_hex_layout.csv
  telescope_config_name: telescope_config/HERA65_config.yaml
sources:
  catalog: 'gaussian_eor_shell'
time:
  Ntimes: 7854   # 24 hours
  integration_time: 11.0
  start_time: 2458098.5521759833
select:
  redundancy: 0.25

fov: 110   # Deg
Nskies: 1
sky_sigma: 0.031      # 31 mK
Nside: 128
